#Table edits and merges for transects


#If new tables are created these file paths will need to be changed

tableImport("raster1", "tran01")
tableImport("raster2", "tran06")
tableImport("raster3", "tran11")

#If new tables are created the names of the filelist variables will need to changed to match those generated by the tableImport functions above
#The name of the variables will be "fileList_" plus an text extension added above in the tableImport function


totalFileListTran <- list(fileList_tran01, fileList_tran06, fileList_tran11)

#Edits each table within the following list

h = 1
hList = c('01','06','11')

#Edits each table within the following list

for (shpLists in totalFileListTran){
  
  
  
  for(file in shpLists){
    
    yearInput = hList[h]
    tableEditTran(file, yearInput)
    
  }
  h = h +1
}

#List of strings which the tableMerge function uses to match fragstat tables

shpLists <- c("shp1", "shp2", "shp3", "shp4", "shp5", "shp6", "shp7", "shp8", "shp9", "shp10")


#This for loop goes through each list within the totalFileListCC and merges the matching shapefile tables
for (shp in shpLists){
  
  tableMergeTran(shp, 'totalFileListTran')
  
}


#Removes all of the singular fragstat tables

rm(shp1tran01, shp2tran01, shp3tran01, shp4tran01, shp5tran01,
   shp6tran01, shp7tran01, shp8tran01, shp9tran01, shp10tran01)
rm(shp1tran06, shp2tran06, shp3tran06, shp4tran06, shp5tran06, 
   shp6tran06, shp7tran06, shp8tran06, shp9tran06, shp10tran06)
rm(shp1tran11, shp2tran11, shp3tran11, shp4tran11, shp5tran11, 
   shp6tran11, shp7tran11, shp8tran11, shp9tran11, shp10tran11)





